language: csharp
solution: Chirper.sln
mono: none
dotnet: 2.1.500

services:
  - docker

install:
  - dotnet restore

script:
  - dotnet build
  - dotnet test
  - docker build -t vijayshinva/chirper:latest -f Chirper.Domain.Host/Dockerfile .
  - docker build -t vijayshinva/chirper-identity:latest -f Chirper.Identity/Dockerfile .
  - docker build -t vijayshinva/chirper-webapi:latest -f Chirper.Domain.WebApi/Dockerfile .
  - docker build -t vijayshinva/chirper-web:latest -f Chirper.Web/Dockerfile .
  - docker build -t vijayshinva/chirper-front-envoy:latest Chirper.Envoy

deploy:
  skip_cleanup: true
  provider: script
  script: chmod +x dockerhub_deploy.sh && ./dockerhub_deploy.sh